config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  resources :users, only: [:show, :edit, :update]
  root to: "rooms#index"

end

app/models/gender.rb
class Gender < ActiveRecord::Base

has_many :users
end

app/models/housemate.rb
class Housemate < ActiveRecord::Base
has_many :users
end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
has_many :users
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :nickname, presence: true

  has_attached_file :avatar,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
                                      content_type: ["image/jpg","image/jpeg","image/png"]

  belongs_to :genders
  belongs_to :housemates
  belongs_to :occupations
  has_many :rooms

  mount_uploader :image, ImageUploader

def age
  date_format = "%Y%m%d"
  (Date.today.strftime(date_format).to_i - birth_day.strftime(date_format).to_i) / 10000
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up).push(:nickname)
    devise_parameter_sanitizer.for(:account_update).push(:nickname, :avatar, :birth_day, :sex, :housemate, :occupation)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_name: room_params[:room_name], room_genre: room_params[:room_genre], room_detail: room_params[:room_detail], user_id: current_user.id)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_name, :room_genre, :room_detail, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @rooms = current_user.rooms.includes(:user).page(params[:page]).per(5).order('created_at DESC')
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :avatar, :birth_day, :sex, :housemate, :occupation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Roomを投稿する", new_room_path(current_user) %></li>
      <li><%= link_to "マイページへ", user_path(current_user) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roov</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'common/header' %>
<%= bootstrap_flash %>
<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_name %><br>
    <%= f.text_area :room_name %>
  </div>
  <div class="field">
    <%= f.label :room_genre %><br>
    <%= f.text_area :room_genre %>
  </div>
  <div class="field">
    <%= f.label :room_detail %><br>
    <%= f.text_area :room_detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room name</th>
      <th>Room genre</th>
      <th>Room detail</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_name %></td>
        <td><%= room.room_genre %></td>
        <td><%= room.room_detail %></td>
        <td><%= room.user_id %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room name:</strong>
  <%= @room.room_name %>
</p>

<p>
  <strong>Room genre:</strong>
  <%= @room.room_genre %>
</p>

<p>
  <strong>Room detail:</strong>
  <%= @room.room_detail %>
</p>

<p>
  <strong>User:</strong>
  <%= @room.user_id %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  <h2>登録情報</h2>
  <div class="field">
    <%= f.label :ニックネーム %><br />
    <%= f.text_field :nickname, placeholder:"current_user.nickname" %></div>

  <div class="field">
    <%= f.label :プロフィール画像 %><br />
    <%= f.file_field :image, autofocus: true %>
    <%= image_tag @user.image.thumb.url if @user.image? %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= f.label :生年月日 %><br />
    <%= f.text_field :birth_day, placeholder:"例：19870131", maxlength: "8" %></div>

  <div class="field">
    <%= f.label :性別 %><br />
    <%= f.collection_select :sex, Gender.all, :gender, :gender %></div>

  <div class="field">
    <%= f.label :ハウスメイト %><br />
    <%= f.collection_select :housemate, Housemate.all, :housemate, :housemate %></div>

  <div class="field">
    <%= f.label :職業 %><br />
    <%= f.collection_select :occupation, Occupation.all, :occupation, :occupation %></div>

  <div class="actions">
  <%= f.submit '更新' %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= @user.nickname %>さんのページです
<%= link_to 'プロフィール編集', edit_user_path(current_user) %>

  <h2>会員情報</h2>
  <table>
  <tbody>
  <tr>
    <th>項目</th>
    <th>登録内容</th>
  </tr>
  <tr>
    <td>ニックネーム</td>
    <td><%= current_user.nickname %></td>
  </tr>
  <tr>
    <td>年齢</td>
    <td><%= current_user.age %>歳</td>
  </tr>
  <tr>
    <td>性別</td>
    <td><%= current_user.sex %></td>
  </tr>
  <tr>
    <td>ハウスメイト</td>
    <td><%= current_user.housemate %></td>
  </tr>
  <tr>
    <td>職業</td>
    <td><%= current_user.occupation %></td>
  </tr>
  <tr>
  <td>プロフィール画像</td>
  <td><%= image_tag  current_user.image %></td>
  </tr>
  </tbody>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>